# Generated by Django 5.1.4 on 2024-12-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='GroupFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('finalized_idea_id', models.IntegerField(blank=True, null=True)),
                ('idea_1_id', models.IntegerField(blank=True, null=True)),
                ('idea_2_id', models.IntegerField(blank=True, null=True)),
                ('idea_3_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Group_formation',
            },
        ),
        migrations.CreateModel(
            name='GroupStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('student_batch_link_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Group_students',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('broad_area', models.CharField(blank=True, max_length=255, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('originality_innovativeness', models.TextField(blank=True, null=True)),
                ('key_activities', models.TextField(blank=True, null=True)),
                ('data_sources', models.TextField(blank=True, null=True)),
                ('technology_usage', models.TextField(blank=True, null=True)),
                ('scalability', models.TextField(blank=True, null=True)),
                ('social_impact', models.TextField(blank=True, null=True)),
                ('potent_users', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Idea',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('enrollment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=80, null=True)),
                ('mobileno', models.CharField(max_length=10)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Student_details',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('cretaed_on', models.DateTimeField(blank=True, null=True)),
                ('cretaed_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User_master',
            },
        ),
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('current_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentbatch_current_batch_set', to='api.batch')),
                ('previous_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.batch')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.studentdetails')),
            ],
            options={
                'db_table': 'Student_batch',
            },
        ),
    ]
