# Generated by Django 5.1.4 on 2024-12-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='groupformation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='groupstudents',
            options={},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentbatch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermaster',
            options={},
        ),
    ]
