# Generated by Django 5.1.4 on 2024-12-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbatch',
            name='previous_batch',
        ),
        migrations.RemoveField(
            model_name='studentbatch',
            name='current_batch',
        ),
        migrations.DeleteModel(
            name='GroupFormation',
        ),
        migrations.DeleteModel(
            name='GroupStudents',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.RemoveField(
            model_name='studentbatch',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='UserMaster',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='StudentBatch',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
