# Generated by Django 5.1.4 on 2024-12-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_remove_studentbatch_previous_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'db_table': 'batch',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('broad_area', models.CharField(blank=True, max_length=255, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('originality_innovativeness', models.TextField(blank=True, null=True)),
                ('key_activities', models.TextField(blank=True, null=True)),
                ('data_sources', models.TextField(blank=True, null=True)),
                ('technology_usage', models.TextField(blank=True, null=True)),
                ('scalability', models.TextField(blank=True, null=True)),
                ('social_impact', models.TextField(blank=True, null=True)),
                ('potent_users', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idea',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='GroupFormation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=9)),
                ('finalized_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_group_formations', to='api.idea')),
                ('idea_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_1_group_formations', to='api.idea')),
                ('idea_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_2_group_formations', to='api.idea')),
                ('idea_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_3_group_formations', to='api.idea')),
            ],
            options={
                'verbose_name_plural': 'Group Formations',
                'db_table': 'group_formation',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('enrollment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=80, null=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.batch')),
            ],
            options={
                'verbose_name_plural': 'Student Details',
                'db_table': 'student_details',
            },
        ),
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transition_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('current_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_batches', to='api.batch')),
                ('previous_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_batches', to='api.batch')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_batches', to='api.studentdetails')),
            ],
            options={
                'db_table': 'student_batch',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Mentor', 'Mentor')], default='Student', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to='api.usermaster')),
            ],
            options={
                'db_table': 'user_master',
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_created', to='api.usermaster'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to='api.usermaster'),
        ),
        migrations.CreateModel(
            name='GroupStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='api.groupformation')),
                ('student_batch_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='api.studentbatch')),
            ],
            options={
                'db_table': 'group_students',
                'unique_together': {('group', 'student_batch_link')},
            },
        ),
    ]
