# Generated by Django 5.1.4 on 2025-01-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usermaster_groups_usermaster_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
