# Generated by Django 5.1.4 on 2025-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_studentdetails_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
