# Generated by Django 5.1.4 on 2025-02-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_batch_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='status',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='enrollment_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
