# Generated by Django 5.1.4 on 2025-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_usermaster_otp_remove_usermaster_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
