# Generated by Django 5.1.4 on 2025-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usermaster_otp_usermaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupformation',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
