# Generated by Django 5.1.4 on 2025-03-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tokentracking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokentracking',
            table='token_Tracking',
        ),
    ]
