# Generated by Django 5.1.4 on 2025-03-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tokentracking_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokentracking',
            table='token_tracking',
        ),
    ]
