# Generated by Django 5.1.4 on 2025-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tokentracking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupformation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=9),
        ),
    ]
