# Generated by Django 5.1.4 on 2025-08-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_groupformation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Expertise',
                'db_table': 'expertise',
            },
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='usertype',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Guide', 'Guide')], default='Student', max_length=20),
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'usertype': 'Guide'}, on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guide',
            },
        ),
        migrations.CreateModel(
            name='GuideExpertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_links', to='api.expertise')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_links', to='api.guide')),
            ],
            options={
                'verbose_name_plural': 'Guide Expertise',
                'db_table': 'guide_expertise',
                'unique_together': {('guide', 'expertise')},
            },
        ),
        migrations.CreateModel(
            name='GuideGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_guides', to='api.groupformation')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_groups', to='api.guide')),
            ],
            options={
                'db_table': 'guide_group',
                'unique_together': {('guide', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GuideProjectInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_guides', to='api.groupformation')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_interests', to='api.guide')),
            ],
            options={
                'db_table': 'guide_project_interest',
                'ordering': ['priority'],
                'unique_together': {('guide', 'group')},
            },
        ),
    ]
