# Generated by Django 5.1.4 on 2025-08-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_expertise_alter_usermaster_usertype_guide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='is_frozen',
        ),
        migrations.AddField(
            model_name='guide',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
