# Generated by Django 5.1.4 on 2025-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_guide_is_frozen_guide_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprojectinterest',
            name='priority',
            field=models.CharField(choices=[('P1', 'Priority 1'), ('P2', 'Priority 2'), ('P3', 'Priority 3')], max_length=2),
        ),
    ]
