# Generated by Django 5.1.4 on 2025-09-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_guideprojectinterest_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMaster',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('changes_suggested_prev', models.TextField(blank=True, help_text='Text area to store changes suggested in the previous meeting', max_length=2000, null=True)),
                ('changes_done_prev', models.TextField(help_text='Text area to store changes completed from the previous meeting', max_length=2000)),
                ('suggested_changes_next', models.TextField(help_text='Text area to store suggested changes for the next meeting', max_length=2000)),
                ('guide_remarks', models.TextField(help_text='Text area for guide’s remarks about the meeting or project progress', max_length=2000)),
                ('approval_status', models.BooleanField(default=False, help_text='Boolean field to mark approval status (True = Approved, False = Pending)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the log entry was created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meeting_logs', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_logs', to='api.groupformation')),
            ],
            options={
                'db_table': 'log_master',
                'ordering': ['group_id', 'log_id'],
            },
        ),
    ]
