# Generated by Django 5.1.4 on 2026-03-18 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_logmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='project_documents/')),
                ('status', models.CharField(choices=[('submitted', 'document submitted'), ('guide_revision', 'guide asked revision document'), ('guide_approved', 'guide approved document'), ('admin_revision', 'admin asked revision document'), ('admin_approved', 'admin approved document')], default='submitted', max_length=20)),
                ('is_latest', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.groupformation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('GUIDE', 'Guide'), ('ADMIN', 'Admin')], max_length=10)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.projectdocument')),
            ],
            options={
                'db_table': 'document_comment',
            },
        ),
        migrations.CreateModel(
            name='SubmissionWindow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('submission_start', models.DateTimeField()),
                ('submission_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.batch')),
            ],
            options={
                'db_table': 'submission_window',
            },
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.submissionwindow'),
        ),
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardcopy_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUESTED', 'Requested'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified')], default='NOT_REQUIRED', max_length=20)),
                ('hardcopy_requested_at', models.DateTimeField(blank=True, null=True)),
                ('hardcopy_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hardcopy_verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projectdocument')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupformation')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.submissionwindow')),
            ],
            options={
                'db_table': 'submission_status',
                'unique_together': {('submission', 'group')},
            },
        ),
        migrations.AddConstraint(
            model_name='projectdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('group', 'submission'), name='unique_latest_document_per_group_submission'),
        ),
    ]
