# Generated by Django 5.1.4 on 2026-03-18 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_projectdocument_documentcomment_submissionwindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionwindow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
