# Generated by Django 5.1.4 on 2026-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_submissionwindow_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionwindow',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
