# Generated by Django 5.1.4 on 2026-03-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_submissionwindow_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionwindow',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
