GET http://127.0.0.1:8000/protectedview/ HTTP/1.1
content-type: application/json
Authorization: Bearer 


###
POST http://127.0.0.1:8000/token/refersh/ HTTP/1.1
content-type: application/json

{
    "refresh":""
}


###
POST http://127.0.0.1:8000/login/ HTTP/1/1
content-type: application/json

{
    "email":"nirav20267@gmail.com",
    "password_or_otp":"admin"
}

###
GET http://127.0.0.1:8000/batches/ HTTP/1/1
Authorization: Bearer 

### creating batch api for user according to the access token
POST http://127.0.0.1:8000/batches/ HTTP/1/1
Authorization: Bearer 
Content-Type: application/json

{
    "batch_name":"Major Project 2027"
}

### first login with otp like normal login
POST http://127.0.0.1:8000/login/ HTTP/1/1
content-type: application/json

{
    "email":"niravkumar.r.lad@nuv.ac.in",
    "password_or_otp":"niravlad"
}

### setting password for after first login
POST http://127.0.0.1:8000/set-password/ HTTP/1/1
content-type: application/json
Authorization: Bearer 

{
    "password":"niravlad"
}

### creating single student registration
POST http://127.0.0.1:8000/students/register/ HTTP/1/1
Content-Type: application/json
Authorization: Bearer 

{
    "name":"Zels Sorathiya",
    "email":"zels.s@nuv.ac.in",
    "enrollment_id":"24000859",
    "batch_name":"Major Project 2028"
}

### adding the remaining details after setting the login password on first login
### Update Student Details (Section & Mobile Number)
PUT http://127.0.0.1:8000/update-student-details/
Authorization: Bearer 
Content-Type: application/json

{
    "section": "B2",
    "mobile_no": "0123456789"
}

### first login with otp like normal login for zels
POST http://127.0.0.1:8000/login/ HTTP/1/1
content-type: application/json

{
    "email":"zels.s@nuv.ac.in",
    "password_or_otp":"zelsSorathiya"
}

### setting password for after first login for zels
POST http://127.0.0.1:8000/set-password/ HTTP/1/1
content-type: application/json
Authorization: Bearer 

{
    "password":"zelsSorathiya"
}

### New request to see the students in particualr batches 
GET http://127.0.0.1:8000/batches/Major Project 2028/students/ HTTP/1/1
Content-Type: application/json
Authorization: Bearer 

### TO get student profile details just via login
GET http://127.0.0.1:8000/students/profile/ HTTP/1/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjEwNzIxLCJpYXQiOjE3MzkyMDg5MjEsImp0aSI6ImNmMjlmOWQ1MGRhNzQ3NDhiZjIzOWIzMjdkMzVlNDY3IiwidXNlcl9pZCI6Mzl9.HrsBr1UkaMZCm0lsJPQUWXonwZzGNkws-fa6H8cDL9w

### To get students details for admin or other user via enrollment id
GET http://127.0.0.1:8000/students/24000859 HTTP/1/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjEwNzAzLCJpYXQiOjE3MzkyMDg5MDMsImp0aSI6IjJiZmQ0Y2IxM2VlYTRmMThhMGFmY2E5YjliYzhkNmIwIiwidXNlcl9pZCI6NH0.6nNY7omt_NUkfg58nv7W4QK-_ucqaaU5wc8HwvzF53c





